# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

WORKDIR /app

# Copy package files and install all dependencies (including dev)
COPY package*.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the project using tsc
RUN npm run build

FROM node:lts-alpine

WORKDIR /app

# Copy production package files and install production dependencies only
COPY package*.json ./
RUN npm install --production --ignore-scripts

# Copy built files from builder stage
COPY --from=builder /app/build ./build

EXPOSE 3000

CMD ["node", "build/index.js"]
